package sunset.FrontEnd;

import sunset.BackEnd.DBConnectionMgr;
import sunset.domain.Invoice;
import sunset.domain.Residence;
import sunset.domain.Tenant;

//*************************************************************************************
//  Class Name: AdditionalData
//  Descrption: This class shows the additional data to user in a GUI window
//*************************************************************************************
public class AdditionalData extends javax.swing.JFrame {

    //*******************************************************
    //  initialize GUI without parameters
    //  it shows associate data from tables like invoices, Lease, etc from the database
    //*******************************************************
    public AdditionalData() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
    
    //*******************************************************
    //  Construct GUI with Tenant obj parameter
    //  it shows associate data from tables like invoices, Lease, etc from the database
    //  sets all of the textFields from the GUI 
    //*******************************************************
    public AdditionalData(Tenant tenant) {
         
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        DBConnectionMgr conn = new DBConnectionMgr();
        Tenant tempTenant = conn.getAllDataForTenant(tenant);
        Residence lease = tempTenant.getLease();
        Invoice invoice = lease.getInvoice();
        
        tfName.setText(tenant.getFirstName() +" "+ tenant.getLastName());
        tfLeaseID.setText(Integer.toString(lease.getResID()));
        tfResidenceID.setText(Integer.toString(lease.getResID()));
        
    
        tfStartDate.setText(lease.getStart());
        tfEndDate.setText(lease.getEnd());
        tfDuration.setText(lease.getDuration());
        tfRent.setText(lease.getRentCost());
        tfBillDueDate.setText(invoice.getBillDue());
        tfLastPaid.setText(invoice.getBillPaid());
        tfFirstNtc.setText(invoice.getFirstNot());
        tfLastNtc.setText(invoice.getLastNot());
      
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        lbDuration = new javax.swing.JLabel();
        tfDuration = new javax.swing.JLabel();
        lbStartDate = new javax.swing.JLabel();
        tfStartDate = new javax.swing.JLabel();
        lbEndDate = new javax.swing.JLabel();
        tfEndDate = new javax.swing.JLabel();
        lbRent = new javax.swing.JLabel();
        tfRent = new javax.swing.JLabel();
        lbResidenceID = new javax.swing.JLabel();
        tfResidenceID = new javax.swing.JLabel();
        lbBillDuDate = new javax.swing.JLabel();
        tfBillDueDate = new javax.swing.JLabel();
        lbLeaseID = new javax.swing.JLabel();
        tfLeaseID = new javax.swing.JLabel();
        lbLastPaid = new javax.swing.JLabel();
        tfLastPaid = new javax.swing.JLabel();
        lbFirstNtc = new javax.swing.JLabel();
        tfFirstNtc = new javax.swing.JLabel();
        lbLastNtc = new javax.swing.JLabel();
        tfLastNtc = new javax.swing.JLabel();
        btClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbDollarSign = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        tfName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Additional Information");

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Additional Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 3, 13))); // NOI18N

        lbDuration.setText("Lease Duration:");

        tfDuration.setText("data");

        lbStartDate.setText("Lease Start Date:");

        tfStartDate.setText("Data Not Available!");

        lbEndDate.setText("Lease End Date:");

        tfEndDate.setText("Data Not Available!");

        lbRent.setText("Monthly Rent:");

        tfRent.setText("Data Not Available!");

        lbResidenceID.setText("Residence ID:");

        tfResidenceID.setText("Data Not Available!");

        lbBillDuDate.setText("Bill Due Date:");

        tfBillDueDate.setText("Data Not Available!");

        lbLeaseID.setText("Lease ID:");

        tfLeaseID.setText("Data Not Available!");

        lbLastPaid.setText("Last Paid Date:");

        tfLastPaid.setText("Data Not Available!");

        lbFirstNtc.setText("First Notice Sent On:");

        tfFirstNtc.setText("Data Not Available!");

        lbLastNtc.setText("Last Notice Sent On:");

        tfLastNtc.setText("Data Not Available!");

        btClose.setText("Close");
        btClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCloseActionPerformed(evt);
            }
        });

        jLabel1.setText("Month(s).");

        lbDollarSign.setText("$");

        lbName.setText("Tenant Name:");

        tfName.setText("Data Not Available!");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbLastNtc)
                        .addGap(41, 41, 41)
                        .addComponent(tfLastNtc))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(btClose)))
                .addContainerGap(245, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbName)
                    .addComponent(lbStartDate)
                    .addComponent(lbDuration)
                    .addComponent(lbResidenceID)
                    .addComponent(lbBillDuDate)
                    .addComponent(lbFirstNtc))
                .addGap(39, 39, 39)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfBillDueDate)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(tfDuration)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addComponent(tfStartDate)
                            .addComponent(tfResidenceID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbLastPaid)
                                    .addComponent(lbLeaseID))
                                .addGap(35, 35, 35)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfLeaseID)
                                    .addComponent(tfLastPaid)))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbEndDate, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbRent, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addComponent(lbDollarSign)
                                .addGap(3, 3, 3)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfEndDate)
                                    .addComponent(tfRent))))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfFirstNtc)
                            .addComponent(tfName))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbName)
                    .addComponent(tfName))
                .addGap(14, 14, 14)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDuration)
                    .addComponent(tfDuration)
                    .addComponent(lbRent)
                    .addComponent(tfRent)
                    .addComponent(jLabel1)
                    .addComponent(lbDollarSign))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbStartDate)
                    .addComponent(tfStartDate)
                    .addComponent(lbEndDate)
                    .addComponent(tfEndDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbResidenceID)
                    .addComponent(tfResidenceID)
                    .addComponent(lbLeaseID)
                    .addComponent(tfLeaseID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBillDuDate)
                    .addComponent(tfBillDueDate)
                    .addComponent(lbLastPaid)
                    .addComponent(tfLastPaid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFirstNtc)
                    .addComponent(tfFirstNtc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbLastNtc)
                    .addComponent(tfLastNtc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btClose))
        );
        jLayeredPane1.setLayer(lbDuration, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(tfDuration, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lbStartDate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(tfStartDate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lbEndDate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(tfEndDate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lbRent, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(tfRent, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lbResidenceID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(tfResidenceID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lbBillDuDate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(tfBillDueDate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lbLeaseID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(tfLeaseID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lbLastPaid, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(tfLastPaid, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lbFirstNtc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(tfFirstNtc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lbLastNtc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(tfLastNtc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btClose, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lbDollarSign, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lbName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(tfName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //*******************************************************
    //  Event Handler for Close Button on GUI
    //  it opens back the FindTenant window when clicked
    //  
    //*******************************************************
    private void btCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCloseActionPerformed
        
        dispose();
    }//GEN-LAST:event_btCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdditionalData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdditionalData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdditionalData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdditionalData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdditionalData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lbBillDuDate;
    private javax.swing.JLabel lbDollarSign;
    private javax.swing.JLabel lbDuration;
    private javax.swing.JLabel lbEndDate;
    private javax.swing.JLabel lbFirstNtc;
    private javax.swing.JLabel lbLastNtc;
    private javax.swing.JLabel lbLastPaid;
    private javax.swing.JLabel lbLeaseID;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbRent;
    private javax.swing.JLabel lbResidenceID;
    private javax.swing.JLabel lbStartDate;
    private javax.swing.JLabel tfBillDueDate;
    private javax.swing.JLabel tfDuration;
    private javax.swing.JLabel tfEndDate;
    private javax.swing.JLabel tfFirstNtc;
    private javax.swing.JLabel tfLastNtc;
    private javax.swing.JLabel tfLastPaid;
    private javax.swing.JLabel tfLeaseID;
    private javax.swing.JLabel tfName;
    private javax.swing.JLabel tfRent;
    private javax.swing.JLabel tfResidenceID;
    private javax.swing.JLabel tfStartDate;
    // End of variables declaration//GEN-END:variables
}
