/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 *  Author: Jose Lara
 */
package sunset.FrontEnd;

import java.awt.event.KeyEvent;

/* FILENAME: EditTenant
 * DECRIPTION: EditTenant will allow for the editing of previously saved
 *             Tenant data.
 * @author Jose
 */
public class EditTenant extends javax.swing.JFrame {

    /**
     * Creates new form Edit
     */
    public EditTenant() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbUpdateTenantTitle = new javax.swing.JLayeredPane();
        lbFirstName = new javax.swing.JLabel();
        lbLastName = new javax.swing.JLabel();
        tfFirstName = new javax.swing.JTextField();
        lbStreetAddress = new javax.swing.JLabel();
        tfStreetAddress = new javax.swing.JTextField();
        lbApt = new javax.swing.JLabel();
        tfApt = new javax.swing.JTextField();
        lbCity = new javax.swing.JLabel();
        tfCity = new javax.swing.JTextField();
        lbState = new javax.swing.JLabel();
        lbZip = new javax.swing.JLabel();
        tfZipCode = new javax.swing.JTextField();
        lbTel = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        tfLastName = new javax.swing.JTextField();
        lbDateOfBirth = new javax.swing.JLabel();
        tfPhone = new javax.swing.JFormattedTextField();
        tfState = new javax.swing.JComboBox();
        tfDateOfBirth = new javax.swing.JFormattedTextField();
        rbDefaultAddress = new javax.swing.JRadioButton();
        btHome = new javax.swing.JButton();
        lbLeaseInfoTitle = new javax.swing.JLayeredPane();
        lbLeaseID = new javax.swing.JLabel();
        lbDuration = new javax.swing.JLabel();
        tfDuration = new javax.swing.JTextField();
        lbStartDate = new javax.swing.JLabel();
        tfStartDate = new javax.swing.JTextField();
        lbEndDate = new javax.swing.JLabel();
        tfEndDate = new javax.swing.JTextField();
        tfLeaseID = new javax.swing.JLabel();
        btSave = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        lbRentInfoTitle = new javax.swing.JLayeredPane();
        lbRentCost = new javax.swing.JLabel();
        tfRentCost = new javax.swing.JTextField();
        lbDueDate = new javax.swing.JLabel();
        tfDueDate = new javax.swing.JTextField();
        lbOtherInfoTitle = new javax.swing.JLayeredPane();
        rbLastNotice = new javax.swing.JRadioButton();
        rdLateNotice = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Update Tenant");

        lbUpdateTenantTitle.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update Tenant", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 3, 13))); // NOI18N

        lbFirstName.setText("First:");

        lbLastName.setText("Last:");

        lbStreetAddress.setText("Street");

        lbApt.setText("APT #:");

        lbCity.setText("City:");

        lbState.setText("State:");

        lbZip.setText("Zip Code:");

        lbTel.setText("Tel:");

        lbEmail.setText("Email:");

        lbDateOfBirth.setText("DOB");

        tfPhone.setColumns(10);
        try {
            tfPhone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        tfState.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME", "MI", "MN", "MO", "MS", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WI", "WV", "WY" }));

        tfDateOfBirth.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("YYYY-MM-DD"))));
        tfDateOfBirth.setText("YYYY-MM-DD");

        rbDefaultAddress.setText("Use Complex Address");
        rbDefaultAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbDefaultAddressMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout lbUpdateTenantTitleLayout = new javax.swing.GroupLayout(lbUpdateTenantTitle);
        lbUpdateTenantTitle.setLayout(lbUpdateTenantTitleLayout);
        lbUpdateTenantTitleLayout.setHorizontalGroup(
            lbUpdateTenantTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbUpdateTenantTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lbUpdateTenantTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lbUpdateTenantTitleLayout.createSequentialGroup()
                        .addGroup(lbUpdateTenantTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTel)
                            .addComponent(lbCity))
                        .addGap(27, 27, 27)
                        .addGroup(lbUpdateTenantTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lbUpdateTenantTitleLayout.createSequentialGroup()
                                .addGroup(lbUpdateTenantTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbUpdateTenantTitleLayout.createSequentialGroup()
                                        .addGap(306, 306, 306)
                                        .addComponent(lbApt)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tfApt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tfCity, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbState)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbZip)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(lbUpdateTenantTitleLayout.createSequentialGroup()
                                .addComponent(tfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfEmail))))
                    .addGroup(lbUpdateTenantTitleLayout.createSequentialGroup()
                        .addGroup(lbUpdateTenantTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lbUpdateTenantTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(lbUpdateTenantTitleLayout.createSequentialGroup()
                                    .addComponent(lbFirstName)
                                    .addGap(4, 4, 4))
                                .addComponent(lbStreetAddress, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(lbDateOfBirth))
                        .addGap(20, 20, 20)
                        .addGroup(lbUpdateTenantTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(lbUpdateTenantTitleLayout.createSequentialGroup()
                                .addGroup(lbUpdateTenantTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbLastName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(lbUpdateTenantTitleLayout.createSequentialGroup()
                                .addComponent(tfDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbDefaultAddress)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        lbUpdateTenantTitleLayout.setVerticalGroup(
            lbUpdateTenantTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbUpdateTenantTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lbUpdateTenantTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFirstName)
                    .addComponent(tfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLastName)
                    .addComponent(tfLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lbUpdateTenantTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbDefaultAddress)
                    .addGroup(lbUpdateTenantTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbDateOfBirth)
                        .addComponent(tfDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lbUpdateTenantTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbStreetAddress)
                    .addComponent(tfStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbApt)
                    .addComponent(tfApt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lbUpdateTenantTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lbUpdateTenantTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbState)
                        .addComponent(lbZip)
                        .addComponent(tfZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbCity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lbUpdateTenantTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTel)
                    .addComponent(tfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmail)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        lbUpdateTenantTitle.setLayer(lbFirstName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lbUpdateTenantTitle.setLayer(lbLastName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lbUpdateTenantTitle.setLayer(tfFirstName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lbUpdateTenantTitle.setLayer(lbStreetAddress, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lbUpdateTenantTitle.setLayer(tfStreetAddress, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lbUpdateTenantTitle.setLayer(lbApt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lbUpdateTenantTitle.setLayer(tfApt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lbUpdateTenantTitle.setLayer(lbCity, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lbUpdateTenantTitle.setLayer(tfCity, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lbUpdateTenantTitle.setLayer(lbState, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lbUpdateTenantTitle.setLayer(lbZip, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lbUpdateTenantTitle.setLayer(tfZipCode, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lbUpdateTenantTitle.setLayer(lbTel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lbUpdateTenantTitle.setLayer(lbEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lbUpdateTenantTitle.setLayer(tfEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lbUpdateTenantTitle.setLayer(tfLastName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lbUpdateTenantTitle.setLayer(lbDateOfBirth, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lbUpdateTenantTitle.setLayer(tfPhone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lbUpdateTenantTitle.setLayer(tfState, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lbUpdateTenantTitle.setLayer(tfDateOfBirth, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lbUpdateTenantTitle.setLayer(rbDefaultAddress, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btHome.setText("Home");
        btHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHomeActionPerformed(evt);
            }
        });

        lbLeaseInfoTitle.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update Lease", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 3, 13))); // NOI18N

        lbLeaseID.setText("Lease ID:");

        lbDuration.setText("Duration:");

        lbStartDate.setText("Start Date:");

        lbEndDate.setText("End Date:");

        tfLeaseID.setText("No data found!");

        javax.swing.GroupLayout lbLeaseInfoTitleLayout = new javax.swing.GroupLayout(lbLeaseInfoTitle);
        lbLeaseInfoTitle.setLayout(lbLeaseInfoTitleLayout);
        lbLeaseInfoTitleLayout.setHorizontalGroup(
            lbLeaseInfoTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbLeaseInfoTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lbLeaseInfoTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lbLeaseInfoTitleLayout.createSequentialGroup()
                        .addGroup(lbLeaseInfoTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbStartDate)
                            .addComponent(lbEndDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(lbLeaseInfoTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(tfEndDate)))
                    .addGroup(lbLeaseInfoTitleLayout.createSequentialGroup()
                        .addComponent(lbLeaseID)
                        .addGap(18, 18, 18)
                        .addComponent(tfLeaseID)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbLeaseInfoTitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbDuration)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        lbLeaseInfoTitleLayout.setVerticalGroup(
            lbLeaseInfoTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbLeaseInfoTitleLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(lbLeaseInfoTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLeaseID)
                    .addComponent(tfLeaseID, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lbLeaseInfoTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbStartDate)
                    .addComponent(tfStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lbLeaseInfoTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEndDate)
                    .addComponent(tfEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(lbLeaseInfoTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDuration))
                .addGap(29, 29, 29))
        );
        lbLeaseInfoTitle.setLayer(lbLeaseID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lbLeaseInfoTitle.setLayer(lbDuration, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lbLeaseInfoTitle.setLayer(tfDuration, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lbLeaseInfoTitle.setLayer(lbStartDate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lbLeaseInfoTitle.setLayer(tfStartDate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lbLeaseInfoTitle.setLayer(lbEndDate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lbLeaseInfoTitle.setLayer(tfEndDate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lbLeaseInfoTitle.setLayer(tfLeaseID, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btSave.setText("Save");

        btCancel.setText("Cancel");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        lbRentInfoTitle.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rent Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 3, 13))); // NOI18N

        lbRentCost.setText("Rent Cost:");

        lbDueDate.setText("Due Date:");

        javax.swing.GroupLayout lbRentInfoTitleLayout = new javax.swing.GroupLayout(lbRentInfoTitle);
        lbRentInfoTitle.setLayout(lbRentInfoTitleLayout);
        lbRentInfoTitleLayout.setHorizontalGroup(
            lbRentInfoTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbRentInfoTitleLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(lbRentInfoTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbRentCost)
                    .addComponent(lbDueDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lbRentInfoTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfRentCost, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(tfDueDate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lbRentInfoTitleLayout.setVerticalGroup(
            lbRentInfoTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbRentInfoTitleLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(lbRentInfoTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRentCost)
                    .addComponent(tfRentCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lbRentInfoTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDueDate)
                    .addComponent(tfDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        lbRentInfoTitle.setLayer(lbRentCost, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lbRentInfoTitle.setLayer(tfRentCost, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lbRentInfoTitle.setLayer(lbDueDate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lbRentInfoTitle.setLayer(tfDueDate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbOtherInfoTitle.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Other Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 3, 13))); // NOI18N

        rbLastNotice.setText("Send Last Notice");

        rdLateNotice.setText("Send Late Notice");

        javax.swing.GroupLayout lbOtherInfoTitleLayout = new javax.swing.GroupLayout(lbOtherInfoTitle);
        lbOtherInfoTitle.setLayout(lbOtherInfoTitleLayout);
        lbOtherInfoTitleLayout.setHorizontalGroup(
            lbOtherInfoTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbOtherInfoTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lbOtherInfoTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbLastNotice)
                    .addComponent(rdLateNotice))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lbOtherInfoTitleLayout.setVerticalGroup(
            lbOtherInfoTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbOtherInfoTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbLastNotice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdLateNotice)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lbOtherInfoTitle.setLayer(rbLastNotice, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lbOtherInfoTitle.setLayer(rdLateNotice, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btHome, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSave, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbUpdateTenantTitle)
                            .addComponent(lbOtherInfoTitle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbRentInfoTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbLeaseInfoTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbUpdateTenantTitle)
                    .addComponent(lbLeaseInfoTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbRentInfoTitle)
                    .addComponent(lbOtherInfoTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btHome)
                    .addComponent(btSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHomeActionPerformed
        new MainWindow().setVisible(true);
        dispose();
    }//GEN-LAST:event_btHomeActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        new FindTenant().setVisible(true);
        dispose();
    }//GEN-LAST:event_btCancelActionPerformed

    private void rbDefaultAddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbDefaultAddressMouseClicked
        String defaultAddress = "1234 Main STREET";
        String defaultCity = "Santa Monica";
        String defaultState = "CA";
        String defaultZip = "90403";
        
        tfStreetAddress.setText(defaultAddress);
        tfStreetAddress.setEditable(false);
        tfCity.setText(defaultCity);
        tfCity.setEditable(false);
        tfState.setSelectedItem(defaultState);
        tfState.setEditable(false);
        tfZipCode.setText(defaultZip);
        tfZipCode.setEditable(false);
    }//GEN-LAST:event_rbDefaultAddressMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditTenant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditTenant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditTenant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditTenant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditTenant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btHome;
    private javax.swing.JButton btSave;
    private javax.swing.JLabel lbApt;
    private javax.swing.JLabel lbCity;
    private javax.swing.JLabel lbDateOfBirth;
    private javax.swing.JLabel lbDueDate;
    private javax.swing.JLabel lbDuration;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEndDate;
    private javax.swing.JLabel lbFirstName;
    private javax.swing.JLabel lbLastName;
    private javax.swing.JLabel lbLeaseID;
    private javax.swing.JLayeredPane lbLeaseInfoTitle;
    private javax.swing.JLayeredPane lbOtherInfoTitle;
    private javax.swing.JLabel lbRentCost;
    private javax.swing.JLayeredPane lbRentInfoTitle;
    private javax.swing.JLabel lbStartDate;
    private javax.swing.JLabel lbState;
    private javax.swing.JLabel lbStreetAddress;
    private javax.swing.JLabel lbTel;
    private javax.swing.JLayeredPane lbUpdateTenantTitle;
    private javax.swing.JLabel lbZip;
    private javax.swing.JRadioButton rbDefaultAddress;
    private javax.swing.JRadioButton rbLastNotice;
    private javax.swing.JRadioButton rdLateNotice;
    private javax.swing.JTextField tfApt;
    private javax.swing.JTextField tfCity;
    private javax.swing.JFormattedTextField tfDateOfBirth;
    private javax.swing.JTextField tfDueDate;
    private javax.swing.JTextField tfDuration;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfEndDate;
    private javax.swing.JTextField tfFirstName;
    private javax.swing.JTextField tfLastName;
    private javax.swing.JLabel tfLeaseID;
    private javax.swing.JFormattedTextField tfPhone;
    private javax.swing.JTextField tfRentCost;
    private javax.swing.JTextField tfStartDate;
    private javax.swing.JComboBox tfState;
    private javax.swing.JTextField tfStreetAddress;
    private javax.swing.JTextField tfZipCode;
    // End of variables declaration//GEN-END:variables
}
